import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gasolineras_can/app/router.dart';
import 'package:gasolineras_can/features/auth/auth_bloc.dart';
import 'firebase_options.dart'; // Make sure this file exists and is generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(BlocProvider(create: (_) => AuthBloc(), child: const MyApp()));
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    final authBloc = context.read<AuthBloc>();
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      title: 'Gasolineras de Canarias',
      theme: ThemeData(primarySwatch: Colors.blue),
      routerConfig: createRouter(authBloc)
    );
  }
}
