import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:gasolineras_can/app/router.dart';
import 'package:gasolineras_can/core/notifications/notification_service.dart';
import 'package:gasolineras_can/features/auth/auth_bloc.dart';
import 'firebase_options.dart'; // Make sure this file exists and is generated by FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await dotenv.load(fileName: ".env");
  await NotificationService.init();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  final authBloc = AuthBloc();
  runApp(BlocProvider.value(value: authBloc, child: MyApp(authBloc: authBloc)));
}

class MyApp extends StatelessWidget {
  final AuthBloc authBloc;
  const MyApp({super.key, required this.authBloc});

  

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      debugShowCheckedModeBanner: false,
      title: 'Gasolineras de Canarias',
      theme: ThemeData(primarySwatch: Colors.blue),
      routerConfig: createRouter(authBloc),
    );
  }
}
 